### ISSUE TITLE
Can no longer join games from the website with mod manager (forced desktop app)

### ISSUE THREAD

**Issue by ghost** [Malte0621/Roblox-Player-Mod-Manager#3]
Roblox finally forced the desktop app upon all users and I can no longer properly join games with the Roblox Player Mod Manager. They have also patched all forms of downgrading your client version to circumvent this, even going as far as ignoring any modifications made to the regedit entry.

**Expected behavior:** Clicking the play button on the Roblox website will send you directly to the game server after clicking "Launch Player."

**Actual behavior:** You are not sent to the game server. You are sent to the Roblox desktop app home page.

**Workaround:** Add the game you want to join to your favorites. Start the Roblox Player Mod Loader, enter the Roblox desktop app, scroll down to the "Favorites" section of the home page, find the game, and then hit play from there. _This does not work for VIP Servers and now it never will work anymore until a fix is released to the mod manager for this issue._

Please fix, thanks. Roblox Corporation is retarded again.

**Comment by diamond3500** [comment]
I fixed it on my fork: https://github.com/diamond3500/Roblox-Player-Mod-Manager
download the latest release

**Comment by ghost** [comment]
Can confirm patched in above fork.
